/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as StaticRouteImport } from './routes/_static/route'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as StaticIndexImport } from './routes/_static/index'
import { Route as AppInboxImport } from './routes/app/inbox'
import { Route as StaticAboutImport } from './routes/_static/about'

// Create/Update Routes

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const StaticRouteRoute = StaticRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const StaticIndexRoute = StaticIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaticRouteRoute,
} as any)

const AppInboxRoute = AppInboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)

const StaticAboutRoute = StaticAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StaticRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_static/about': {
      id: '/_static/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StaticAboutImport
      parentRoute: typeof StaticRouteImport
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxImport
      parentRoute: typeof AppRouteImport
    }
    '/_static/': {
      id: '/_static/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StaticIndexImport
      parentRoute: typeof StaticRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface StaticRouteRouteChildren {
  StaticAboutRoute: typeof StaticAboutRoute
  StaticIndexRoute: typeof StaticIndexRoute
}

const StaticRouteRouteChildren: StaticRouteRouteChildren = {
  StaticAboutRoute: StaticAboutRoute,
  StaticIndexRoute: StaticIndexRoute,
}

const StaticRouteRouteWithChildren = StaticRouteRoute._addFileChildren(
  StaticRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PathlessLayoutRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof StaticAboutRoute
  '/app/inbox': typeof AppInboxRoute
  '/': typeof StaticIndexRoute
  '/app/': typeof AppIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PathlessLayoutRoute
  '/about': typeof StaticAboutRoute
  '/app/inbox': typeof AppInboxRoute
  '/': typeof StaticIndexRoute
  '/app': typeof AppIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_static': typeof StaticRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/_static/about': typeof StaticAboutRoute
  '/app/inbox': typeof AppInboxRoute
  '/_static/': typeof StaticIndexRoute
  '/app/': typeof AppIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/app' | '/about' | '/app/inbox' | '/' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/app/inbox' | '/' | '/app'
  id:
    | '__root__'
    | '/_static'
    | '/app'
    | '/_pathlessLayout'
    | '/_static/about'
    | '/app/inbox'
    | '/_static/'
    | '/app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  StaticRouteRoute: typeof StaticRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  StaticRouteRoute: StaticRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_static",
        "/app",
        "/_pathlessLayout"
      ]
    },
    "/_static": {
      "filePath": "_static/route.tsx",
      "children": [
        "/_static/about",
        "/_static/"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/inbox",
        "/app/"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx"
    },
    "/_static/about": {
      "filePath": "_static/about.tsx",
      "parent": "/_static"
    },
    "/app/inbox": {
      "filePath": "app/inbox.tsx",
      "parent": "/app"
    },
    "/_static/": {
      "filePath": "_static/index.tsx",
      "parent": "/_static"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
